name = "hugo-menu"
license = "MIT"
description = "Generate food and drink menus for restaurants, bars, events or just at home."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/gentleadam/hugo-menu"

# If you have a running demo of the theme.
demosite = "https://gentleadam.github.io/hugo-menu/"

tags = ["business", "food", "drink", "events", "dining"]

# If the theme has a single author
[author]
    name = "gentleadam"
    homepage = "https://github.com/gentleadam"